name: Github actions

on:
  push:
    branches:
      - "**"
  pull_request:
    types:
      - opened

jobs:
  validation-eslint:
    name: Validation eslint
    uses: alexis-gss/github-workflows/.github/workflows/validation-eslint.yml@master
  deployment:
    name: Deployment production
    needs: ['validation-eslint']
    uses: alexis-gss/github-workflows/.github/workflows/deployment.yml@master
    secrets: inherit
    if: github.ref == 'refs/heads/master'